---
- name: Install Redis package
  apt: pkg=redis-server update_cache=yes cache_valid_time=3600

- meta: flush_handlers

- name: Start redis-server service
  service: name=redis-server state=started

- name: Wait for 6379 to respond
  wait_for: port=6379
