---
- name: Install Redis package
  apt: pkg=redis-server update_cache=yes cache_valid_time=3600

- meta: flush_handlers

- name: Create monit config
  notify: restart monit
  copy:
    dest: /etc/monit/conf.d/redis-server
    content: |
      check process redis-service with pidfile /var/run/redis/redis-server.pid
        start program = "/etc/init.d/redis-server start"
        stop program = "/etc/init.d/redis-server stop"
        if failed port 6379 then restart

- name: Start redis-server service
  service: name=redis-server state=started

- name: Wait for 6379 to respond
  wait_for: port=6379
