---
- name: Install packages
  apt: pkg=dsc20 update_cache=yes cache_valid_time=3600

- name: Create directories
  file: path="{{ item }}" state=directory
  with_items:
    - /srv/cassandra
    - /srv/cassandra/commitlog
    - /srv/cassandra/data
    - /srv/cassandra/saved_caches

- name: Configuring properties
  notify: restart cassandra
  template: src=cassandra.yaml.j2 dest=/etc/cassandra/cassandra.yaml owner=cassandra group=cassandra mode=0644

- name: Configuring env properties
  notify: restart cassandra
  template: src=cassandra-env.sh.j2 dest=/etc/cassandra/cassandra-env.sh owner=cassandra group=cassandra mode=0644

- name: Create monit config
  notify: restart monit
  copy:
    dest: /etc/monit/conf.d/cassandra
    content: |
      check process cassandra with pidfile /var/run/cassandra/cassandra.pid
        start program = "/etc/init.d/cassandra start"
        stop program = "/etc/init.d/cassandra stop"
        if failed port 9160 then restart

- meta: flush_handlers

- name: Start service
  service: name=cassandra state=started

- name: Wait for 9160 to respond
  wait_for: port=9160
