---
# This is used for both the main elasticsearch install, and the local elasticsearch used by Marvel.

- name:
  apt: pkg=elasticsearch=0.90.12 update_cache=yes cache_valid_time=3600

- name: Installing Elasticsearch Head
  notify: restart elasticsearch
  command: creates=/usr/share/elasticsearch/plugins/head /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head

- name: Configuring directories
  file: path=/srv/elasticsearch state=directory

- name: Configuring Elasticsearch node
  notify: restart elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644

- name: Configuring Elasticsearch env
  notify: restart elasticsearch
  template: src=elasticsearch.in.sh.j2 dest=/usr/share/elasticsearch/bin/elasticsearch.in.sh owner=elasticsearch group=elasticsearch mode=0644

- name: Configuring Elasticsearch logging
  notify: restart elasticsearch
  template: src=logging.yml.j2 dest=/etc/elasticsearch/logging.yml owner=elasticsearch group=elasticsearch mode=0644

- name: Create monit config
  notify: restart monit
  copy:
    dest: /etc/monit/conf.d/elasticsearch
    content: |
      check process elasticsearch with pidfile /var/run/elasticsearch.pid
        start program = "/etc/init.d/elasticsearch start"
        stop program = "/etc/init.d/elasticsearch stop"
        if failed port 9300 then restart

- name: Installing Elasticsearch Head
  notify: restart elasticsearch
  command: creates=/usr/share/elasticsearch/plugins/head /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head

- meta: flush_handlers

- name: Start service
  monit: state=started name=elasticsearch

- name: Wait for 9300 to respond
  wait_for: port=9300
