---
# Basic apt repository setup.

- name: Install Elasticsearch APT repository
  notify: update apt
  copy:
    dest: /etc/apt/sources.list.d/elasticsearch.list
    mode: 0644
    content: "deb http://packages.elasticsearch.org/elasticsearch/1.2/debian stable main"

- name: Install Elasticsearch APT GPG key
  notify: update apt
  apt_key: id=D88E42B4 url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Install datastax APT repository
  notify: update apt
  copy:
    dest: /etc/apt/sources.list.d/datastax.list
    mode: 0644
    content: "deb http://debian.datastax.com/community stable main"

- name: Install datastax APT GPG key
  notify: update apt
  apt_key: id=B999A372 url=https://debian.datastax.com/debian/repo_key

- meta: flush_handlers
