---
- name: Kernel Tweaks
  notify: update sysctl
  copy:
    dest: /etc/sysctl.d/60-dev-env.conf
    content: |
      # Increase the maximum number of memory map areas a process may have
      vm.max_map_count=131072
