---

# Prevent paging.
- name: Unlimited memlock default
  lineinfile : line="* - memlock unlimited" dest=/etc/security/limits.conf

- name: Unlimited memlock root
  lineinfile : line="root - memlock unlimited" dest=/etc/security/limits.conf

# Increase the number of FDs, 1024 is silly.
- name: 32k open files default
  lineinfile : line="* - nofile 32768" dest=/etc/security/limits.conf

- name: 32k open files root
  lineinfile : line="root - nofile 32768" dest=/etc/security/limits.conf
